### ISSUE TITLE
Streamline deployment

### ISSUE THREAD

**Issue by senderle** [joelslee/textbook#1]
This is a pretty generic issue and I am not sure what the close criteria will be. I am planning to leave it open until I feel confident that we have reached something near the minimum possible deployment complexity. Some of the things that will factor into that:

- [ ] Determining how easy it is to set up wildcard domains of the kind we need. Ideally it would be possible to configure a single wildcard domain or subdomain to route all traffic to a given IP. Traefik can then handle the routing from there. This would mean that even though the app uses multiple domain names, the user would only have to configure one wildcard domain. If this is hard or impossible we may need to revisit the multiple subdomain strategy. **In fact, I am starting to think the approach described in #5 is better**. We should try that first and see if it works well, and seriously consider using it instead.

- [x] Organizing the user-facing input folders in an sensible way. Right now we have two input folders at the root level, and one inside `text_to_md`. They should at least all be at the root; but possibly the best thing would be to have them all inside a single folder with a name that makes it clear that it's where all the input goes. 

- [x] Looking into the possibility of creating a UI for uploading. This would be really cool: basically, we would build a django-based upload form that would allow users to provide texts, corpora, and keywords via the web. 

- [x] Create an automated generator for `.envs`. This is #7.

- [ ] Documentation. This will have its own issues (#2 and #3) but this issue can't be closed until they both are.

**Comment by joelsjlee** [comment]
Update on the second item:
I have created a folder at the root called `input` that has three additional folders inside it, `texts, keywords,` and  `articles` so the user can easily input all three in one location. Although keywords only requires one .txt file, it seemed best to give it its own folder to make it clear to the user.

I updated these changes with the docker-compose.yml file, and deleted `context` (which inside had the keywords and articles). I left `text_to_md` alone for now, I'm not sure what to do with the `csvs` and `texts` folders, as it was Vince's set up (although I suspect we can go ahead and delete `text_to_md/texts/`).

All these updates are on my branch.

**Comment by senderle** [comment]
I think the UI and Documentation items above will be done soon, and then it may be time to move on; I am not sure it makes sense to worry about the domain name stuff at the moment. So this will be left open for now, but is low priority.
